apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  namespace: k8s-post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - image: evgkapl/user-service:1.0.0
          name: user-service-app
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-user           # The ConfigMap this value comes from.
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service-user:5438/user-service-db?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-user           # The ConfigMap this value comes from.
                  key: POSTGRES_USER
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-app
  namespace: k8s-post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service-app
  template:
    metadata:
      labels:
        app: post-service-app
    spec:
      containers:
        - image: evgkapl/post-service:1.0.0
          name: post-service-app
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-post           # The ConfigMap this value comes from.
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service-post:5439/post-service-db?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-post           # The ConfigMap this value comes from.
                  key: POSTGRES_USER
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
