apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config-post
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS posts (
        id              bigserial
        primary key,
        author_id bigint,
        posted_at timestamp(6),
        text      varchar(255)
    );
