apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config-user
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id              bigserial
        primary key,
        amount_of_posts integer,
        username        varchar(255)
    );
