apiVersion: v1
kind: Namespace
metadata:
  name: k8s-post-service

---

apiVersion: v1
kind: Service
metadata:
  name: post-app
  namespace: k8s-post-service
spec:
  type: LoadBalancer
  selector:
    app: post-service
  ports:
    - protocol: "TCP"
      port: 8081
      targetport: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: k8s-post-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetport: 8080

---

apiVersion: v1
