apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-user
  namespace: k8s-post-service
  labels:
    app: postgres
data:
  POSTGRES_DB: user-service-db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
