apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-post
  namespace: k8s-post-service
  labels:
    app: postgres
data:
  POSTGRES_DB: post-service-db
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
