apiVersion: v1
kind: StorageClass
metadata:
  name: post-manual-local-storage-class
  namespace: k8s-post-service
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

---

apiVersion: v1
kind: StorageClass
metadata:
  name: user-manual-local-storage-class
  namespace: k8s-post-service
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-post  # Sets name of PVC
  namespace: k8s-post-service
  labels:
    app: postgres-post
spec:
  storageClassName: post-manual-local-storage-class
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-post-local  # Sets PV's name
  namespace: k8s-post-service
  labels:
    type: local  # Sets PV's type to local
    app: postgres-post
spec:
  storageClassName: post-manual-local-storage-class
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/yauhenikapliarchuk/Documents/learning/EPAM/KUBERNETIS/MODULE_1/data/post
    type: DirectoryOrCreate

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-user  # Sets name of PVC
  namespace: k8s-post-service
  labels:
    app: postgres-user
spec:
  storageClassName: user-manual-local-storage-class
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-user-local  # Sets PV's name
  namespace: k8s-post-service
  labels:
    type: local  # Sets PV's type to local
    app: postgres-user
spec:
  storageClassName: user-manual-local-storage-class
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/yauhenikapliarchuk/Documents/learning/EPAM/KUBERNETIS/MODULE_1/data/user
    type: DirectoryOrCreate

---
