apiVersion: v1
kind: Service
metadata:
  name: postgres-service-post # Sets service name
  namespace: k8s-post-service
  labels:
    app: postgres-post-svc # Labels and Selectors
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
      nodePort: 32128
  selector:
    app: postgres-post-db-pod

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service-user # Sets service name
  namespace: k8s-post-service
  labels:
    app: postgres-user-svc # Labels and Selectors
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
      nodePort: 32129
  selector:
    app: postgres-user-db-pod

---
#
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: postgres-service-post
#  namespace: k8s-post-service
#subsets:
#  - addresses:
#      - ip: 10.10.1.1
#    ports:
#      - port: 5439
#        name: postgres-service-post
#
#---
#
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: postgres-service-user
#  namespace: k8s-post-service
#subsets:
#  - addresses:
#      - ip: 10.10.1.2
#    ports:
#      - port: 5438
#        name: postgres-service-user

